name: Deploy to AWS Beanstalk

on:
  workflow_dispatch:

env:
  AWS_REGION: "eu-north-1"
  EB_APP_NAME: "hackaton-mvp-team"
  EB_ENV_NAME: "Hackaton-mvp-team-env"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: echo "VERSION_LABEL=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: Package Application
        run: zip -r deploy_package.zip . -x "*.git*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_VALUE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://${{ secrets.S3_BUCKET }}/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ vars.EB_APP_NAME }} \
          --source-bundle S3Bucket=${{ secrets.S3_BUCKET }},S3Key="deploy_package.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name ${{ vars.EB_ENV_NAME }} --version-label "ver-${{ github.sha }}"