name: Deploy to AWS Beanstalk

on:
  workflow_dispatch:

env:
  AWS_REGION: "eu-north-1"
  EB_APP_NAME: "hackaton-mvp-team"
  EB_ENV_NAME: "Hackaton-mvp-team-env"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: echo "VERSION_LABEL=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: Package Application
        run: zip -r deploy_package.zip . -x "*.git*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_VALUE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://${{ secrets.S3_BUCKET }}/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APP_NAME }} \
          --source-bundle S3Bucket=${{ secrets.S3_BUCKET }},S3Key="deploy_package.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${{ env.EB_ENV_NAME }}" \
            --version-label "ver-${{ github.sha }}" \
            --option-settings \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=MONGO_URI,Value="${{ secrets.MONGO_URI }}" \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=MONGO_DB_NAME,Value="${{ secrets.MONGO_DB_NAME }}" \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=JWT_SECRET_KEY,Value="${{ secrets.JWT_SECRET_KEY }}" \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=AWS_ACCESS_KEY_ID,Value="${{ secrets.AWS_SECRET_KEY_ID }}" \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=AWS_SECRET_ACCESS_KEY,Value="${{ secrets.AWS_SECRET_KEY_VALUE }}" \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=S3_BUCKET_RESOURCES,Value="${{ secrets.S3_BUCKET_RESOURCES }}" \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=S3_REGION,Value="${{ env.AWS_REGION }}" \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=CLOUDFRONT_DISTRIBUTION,Value="${{ secrets.CLOUDFRONT_DISTRIBUTION }}" 
